version: 2.1

commands:

  save-maven-cache:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}

  restore-maven-cache:
    steps:
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}


references:

  workspace-root: &workspace-root
                    /tmp/workspace

jobs:

  compile-test-deploy:
    working_directory: *workspace-root
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - restore-maven-cache
      - run: chmod +x mvnw && ./mvnw -s .circleci/settings.xml deploy
      - save-maven-cache




